export const docsPositions = [
  "docs/index.mdx",
  "docs/video-guides/index.mdx",
  "docs/video-guides/introduction.mdx",
  "docs/video-guides/intro-to-livepeer.mdx",
  "docs/video-guides/start-live-streaming/index.mdx",
  "docs/video-guides/start-live-streaming/create-a-stream.mdx",
  "docs/video-guides/start-live-streaming/get-an-api-key.mdx",
  "docs/video-guides/using-livepeer-in-your-app/index.mdx",
  "docs/video-guides/using-livepeer-in-your-app/introduction.mdx",
  "docs/api-reference/index.mdx",
  "docs/api-reference/authentication.mdx",
  "docs/api-reference/stream/index.mdx",
  "docs/api-reference/stream/stream-object.mdx",
  "docs/api-reference/stream/post-create-a-stream-object.mdx",
];
